### ISSUE TITLE
Using same constants as Sugar Calendar plugin

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/custom-functions#21]
Funny oops here.

The PHP constants being defined at the top of the plugin are using the `SC_` prefix, which just happens to be the same prefix used by the main Sugar Calendar plugin.
```php
define( 'SC_PLUGIN_DIR', dirname( __FILE__ ) );
define( 'SC_PLUGIN_INCLUDES', SC_PLUGIN_DIR . '/includes/' );
define( 'SC_PLUGIN_INTEGRATIONS', SC_PLUGIN_INCLUDES . 'integrations/' );
$sc_theme = wp_get_theme();
define( 'SC_THEME_VERSION', $sc_theme->get( 'Version' ) );
```
This results in SC Custom Functions and Sugar Calendar (the plugin) being unable to be activated on the same site.

Let's change the constants here since it's for private, internal use only.

**Comment by SeanChDavis** [comment]
@pippinsplugins You should be good to go on the live site now.
