### ISSUE TITLE
Add hero promo area and pricing table adjustments

### ISSUE THREAD

**Issue by SeanChDavis** [sugarcalendar/custom-functions#4]
For BFCM, we'll display a custom hero area above the current hero area. This will be "activated" and "deactivated" based on the state of the BFCM discount code.

**Comment by SeanChDavis** [comment]
Okay finally got this up on staging: http://staging.sugarcalendar.com/

Please ignore _everything_ besides the promotional hero. The staging site isn't fully set up like the live site is (my local dev site is an exact clone, though).

![sc-site-promo-hero-area](https://user-images.githubusercontent.com/2359131/69770883-8a5a3180-113f-11ea-8892-b36604cbf3fa.png)

**Comment by pippinsplugins** [comment]
❤️
